name: Go Example Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/15 * * * 1-6"

jobs:
  BuildGo:
    runs-on: ubuntu-latest
    env:
      FILE_NAME: hello-server

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.16'

      - name: Build for Linux
        run: |
          go build $FILE_NAME.go
          echo "Build for Linux completed"

      - name: Upload artifact for Linux
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: ./${{ env.FILE_NAME }}

      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build $FILE_NAME.go
          echo "Build for Windows completed"

      - name: Upload artifact for Windows
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: ./${{ env.FILE_NAME }}.exe

  download-and-run-linux:
    runs-on: ubuntu-latest
    needs: BuildGo  # Dependência do job BuildGo
    steps:
      - uses: actions/checkout@v4

      - name: Download Linux artifact
        uses: actions/download-artifact@v3
        with:
          name: linux

      - name: List directory contents
        run: ls -l

      - name: Run run.sh script
        run: source ./run.sh

  download-only-windows:
    runs-on: windows-latest
    needs: BuildGo  # Dependência do job BuildGo
    steps:
      - uses: actions/checkout@v4

      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: windows
